name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Set tag
        id: set_tag
        run: |
          IMAGE_REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          TAG="ghcr.io/${IMAGE_REPOSITORY}/devimage:${GITHUB_SHA}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "image_tag set to $TAG"

  build-container:
    runs-on: ubuntu-latest
    needs: setup-environment
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push devcontainer image with cache
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: true
          tags: ${{ needs.setup-environment.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  lint-client:
    runs-on: ubuntu-latest
    needs: [setup-environment, build-container]
    container:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    steps:
      - run: echo "Lint client"

  unit-test-client:
    runs-on: ubuntu-latest
    needs: [setup-environment, lint-client]
    container:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    steps:
      - run: echo "Unit test client"

  build-client:
    runs-on: ubuntu-latest
    needs: [setup-environment, unit-test-client]
    container:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    steps:
      - run: echo "Build client"

  lint-server:
    runs-on: ubuntu-latest
    needs: [setup-environment, build-container]
    container:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    steps:
      - run: echo "Lint server"

  unit-test-server:
    runs-on: ubuntu-latest
    needs: [setup-environment, lint-server]
    container:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    steps:
      - run: echo "Unit test server"

  build-server:
    runs-on: ubuntu-latest
    needs: [setup-environment, unit-test-server]
    container:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    steps:
      - run: echo "Build server"

  create-server-runtime:
    runs-on: ubuntu-latest
    needs: [setup-environment, build-server]
    container:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    steps:
      - run: echo "Create server runtime container"

  integration-test:
    runs-on: ubuntu-latest
    needs: create-server-runtime
    steps:
      - run: echo "Run integration tests"

  e2e-test:
    runs-on: ubuntu-latest
    needs: [build-client, integration-test]
    steps:
      - run: echo "Run E2E tests"

  deploy-client:
    runs-on: ubuntu-latest
    needs: e2e-test
    if: github.event_name == 'release'
    steps:
      - run: echo "Deploy client"

  deploy-server:
    runs-on: ubuntu-latest
    needs: [e2e-test, create-server-runtime]
    if: github.event_name == 'release'
    steps:
      - run: echo "Deploy server"
